# Generated by Django 3.2 on 2021-04-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_auto_20210428_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralaudio',
            name='descricao',
            field=models.TextField(blank=True, default='Sem descrição', null=True),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='descricao',
            field=models.TextField(blank=True, default='Sem descrição', null=True),
        ),
        migrations.AlterField(
            model_name='diversos',
            name='descricao',
            field=models.TextField(blank=True, default='Sem descrição', null=True),
        ),
        migrations.AlterField(
            model_name='ems',
            name='descricao',
            field=models.TextField(blank=True, default='Sem descrição', null=True),
        ),
        migrations.AlterField(
            model_name='par2000t',
            name='descricao',
            field=models.TextField(blank=True, default='Sem descrição', null=True),
        ),
        migrations.AlterField(
            model_name='radios',
            name='descricao',
            field=models.TextField(blank=True, default='Sem descrição', null=True),
        ),
        migrations.AlterField(
            model_name='telefonia',
            name='descricao',
            field=models.TextField(blank=True, default='Sem descrição', null=True),
        ),
    ]
