# Generated by Django 3.2 on 2021-04-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_auto_20210428_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralaudio',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diversos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ems',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='par2000t',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radios',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telefonia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UltimosRegistros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.situacao')),
            ],
        ),
        migrations.AddField(
            model_name='centralaudio',
            name='ultimos_registros',
            field=models.ManyToManyField(to='equipamentos.UltimosRegistros'),
        ),
        migrations.AddField(
            model_name='consoles',
            name='ultimos_registros',
            field=models.ManyToManyField(to='equipamentos.UltimosRegistros'),
        ),
        migrations.AddField(
            model_name='diversos',
            name='ultimos_registros',
            field=models.ManyToManyField(to='equipamentos.UltimosRegistros'),
        ),
        migrations.AddField(
            model_name='ems',
            name='ultimos_registros',
            field=models.ManyToManyField(to='equipamentos.UltimosRegistros'),
        ),
        migrations.AddField(
            model_name='par2000t',
            name='ultimos_registros',
            field=models.ManyToManyField(to='equipamentos.UltimosRegistros'),
        ),
        migrations.AddField(
            model_name='radios',
            name='ultimos_registros',
            field=models.ManyToManyField(to='equipamentos.UltimosRegistros'),
        ),
        migrations.AddField(
            model_name='telefonia',
            name='ultimos_registros',
            field=models.ManyToManyField(to='equipamentos.UltimosRegistros'),
        ),
    ]
