# Generated by Django 3.2 on 2021-04-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_alter_ultimosregistros_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='par2000t',
            name='ultimos_registros',
        ),
    ]
