# Generated by Django 3.2 on 2021-04-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0010_alter_par2000t_ultimos_registros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimosregistros',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
