# Generated by Django 3.2 on 2021-04-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0011_alter_ultimosregistros_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='par2000t',
            name='ultimos_registros',
        ),
        migrations.AddField(
            model_name='par2000t',
            name='ultimo_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
