# Generated by Django 3.2 on 2021-04-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0012_auto_20210429_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralaudio',
            name='ultimos_registros',
        ),
        migrations.RemoveField(
            model_name='consoles',
            name='ultimos_registros',
        ),
        migrations.RemoveField(
            model_name='diversos',
            name='ultimos_registros',
        ),
        migrations.RemoveField(
            model_name='ems',
            name='ultimos_registros',
        ),
        migrations.RemoveField(
            model_name='radios',
            name='ultimos_registros',
        ),
        migrations.RemoveField(
            model_name='telefonia',
            name='ultimos_registros',
        ),
        migrations.AddField(
            model_name='centralaudio',
            name='ultimo_registro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consoles',
            name='ultimo_registro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diversos',
            name='ultimo_registro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ems',
            name='ultimo_registro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='radios',
            name='ultimo_registro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='telefonia',
            name='ultimo_registro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='UltimosRegistros',
        ),
    ]
