# Generated by Django 3.2 on 2021-04-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralaudio',
            name='situacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='situacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diversos',
            name='situacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ems',
            name='situacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='par2000t',
            name='situacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='radios',
            name='situacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='telefonia',
            name='situacao',
            field=models.IntegerField(),
        ),
    ]
