# Generated by Django 3.2 on 2021-04-24 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_auto_20210423_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('situacao_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='centralaudio',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.situacao'),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.situacao'),
        ),
        migrations.AlterField(
            model_name='diversos',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.situacao'),
        ),
        migrations.AlterField(
            model_name='ems',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.situacao'),
        ),
        migrations.AlterField(
            model_name='par2000t',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.situacao'),
        ),
        migrations.AlterField(
            model_name='radios',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.situacao'),
        ),
        migrations.AlterField(
            model_name='telefonia',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.situacao'),
        ),
    ]
